// AUTOGENERATED FILE. DO NOT EDIT IT

{{.Body }}

func (n *{{.Struct}}) Initialize() { }
func (n *{{.Struct}}) Terminate(status Status) { }

func (n *{{.Struct}}) IsSuccess() bool { return n.Status == SUCCESS }
func (n *{{.Struct}}) IsFailure() bool { return n.Status == FAILURE }
func (n *{{.Struct}}) IsRunning() bool { return n.Status == RUNNING }
func (n *{{.Struct}}) IsTerminated() bool { return n.Status == SUCCESS || n.Status == FAILURE }

func (n *{{.Struct}}) Reset() { n.Status = INVALID }

func (n *{{.Struct}}) Tick() Status {
  if n.Status != RUNNING { n.Initialize() }
  status := n.Update()
  if n.Status != RUNNING { n.Terminate(status) }

  return status
}

// DECORATOR SECTION
func (n *{{.Struct}}) HasNoChild() bool {
  return n.Child == nil
}

func (n *{{.Struct}}) AddChild(child Behavior) {
  n.Child = child
}
