// AUTOGENERATED FILE. DO NOT EDIT IT

// template composite.go

package ai

import (
  _"fmt"
)

type Forest struct {
  Status Status

  Children []Behavior
}

func NewForest() *Forest {
  return &Forest{}
}

func (n *Forest) Update() Status {
	for _, child := range n.Children {
		child.Tick()
	}

  return RUNNING
}


func (n *Forest) Initialize() { }
func (n *Forest) Terminate(status Status) { }

func (n *Forest) IsSuccess() bool { return n.Status == SUCCESS }
func (n *Forest) IsFailure() bool { return n.Status == FAILURE }
func (n *Forest) IsRunning() bool { return n.Status == RUNNING }
func (n *Forest) IsTerminated() bool { return n.Status == SUCCESS || n.Status == FAILURE }

func (n *Forest) Reset() { n.Status = INVALID }

func (n *Forest) Tick() Status {
  if n.Status != RUNNING { n.Initialize() }
  status := n.Update()
  if n.Status != RUNNING { n.Terminate(status) }

  return status
}

// COMPOSITE SECTION
func (n *Forest) IsEmpty() bool {
  return len(n.Children) == 0
}

func (n *Forest) AddChildren(children ...Behavior) {
  n.Children = append(n.Children, children...)
}
