// AUTOGENERATED FILE. DO NOT EDIT IT

// template decorator.go

package ai

import (
  _"fmt"
)

type Inveter struct {
  Status Status

  Child Behavior
}

func NewInveter(child Behavior) *Inveter {
  return &Inveter{
    Child: child,
  }
}

func (n *Inveter) Update() Status {
  status := n.Child.Tick()

  if status == SUCCESS { return FAILURE } else if status == FAILURE { return SUCCESS }

  return status
}


func (n *Inveter) Initialize() { }
func (n *Inveter) Terminate(status Status) { }

func (n *Inveter) IsSuccess() bool { return n.Status == SUCCESS }
func (n *Inveter) IsFailure() bool { return n.Status == FAILURE }
func (n *Inveter) IsRunning() bool { return n.Status == RUNNING }
func (n *Inveter) IsTerminated() bool { return n.Status == SUCCESS || n.Status == FAILURE }

func (n *Inveter) Reset() { n.Status = INVALID }

func (n *Inveter) Tick() Status {
  if n.Status != RUNNING { n.Initialize() }
  status := n.Update()
  if n.Status != RUNNING { n.Terminate(status) }

  return status
}

// DECORATOR SECTION
func (n *Inveter) HasNoChild() bool {
  return n.Child == nil
}

func (n *Inveter) AddChild(child Behavior) {
  n.Child = child
}
