// AUTOGENERATED FILE. DO NOT EDIT IT

// template composite.go

package ai

import (
  _"fmt"
)


type MemSelector struct {
  Status Status

  Children []Behavior
  Index int
}

func NewMemSelector(children ...Behavior) *MemSelector {
  return &MemSelector{
    Children: children,
    Index: 0,
  }
}

func (n *MemSelector) Update() Status {
	if n.IsEmpty() { return SUCCESS }

	for index := n.Index; index < len(n.Children); index++ {
    child := n.Children[index]
		status := child.Tick()

		if status != FAILURE { return status }
	}

	return FAILURE
}


func (n *MemSelector) Initialize() { }
func (n *MemSelector) Terminate(status Status) { }

func (n *MemSelector) IsSuccess() bool { return n.Status == SUCCESS }
func (n *MemSelector) IsFailure() bool { return n.Status == FAILURE }
func (n *MemSelector) IsRunning() bool { return n.Status == RUNNING }
func (n *MemSelector) IsTerminated() bool { return n.Status == SUCCESS || n.Status == FAILURE }

func (n *MemSelector) Reset() { n.Status = INVALID }

func (n *MemSelector) Tick() Status {
  if n.Status != RUNNING { n.Initialize() }
  status := n.Update()
  if n.Status != RUNNING { n.Terminate(status) }

  return status
}

// COMPOSITE SECTION
func (n *MemSelector) IsEmpty() bool {
  return len(n.Children) == 0
}

func (n *MemSelector) AddChildren(children ...Behavior) {
  n.Children = append(n.Children, children...)
}
