// AUTOGENERATED FILE. DO NOT EDIT IT

// template composite.go

package ai

import (
  "game/pidgeot-socket/ecs"
)

type Sequence struct {
  Status Status
  Children []Behavior

  World *ecs.Manager
  Eid ecs.EID
}

func NewSequence(eid ecs.EID, world *ecs.Manager, children ...Behavior) *Sequence {
  return &Sequence{
    Eid: eid,
    World: world,
    Children: children,
  }
}

func (n *Sequence) Update() Status {
	if n.IsEmpty() { return SUCCESS }

	for _, child := range n.Children {
		status := child.Tick()

		if status != SUCCESS { return status }
	}

	return SUCCESS
}


func (n *Sequence) Initialize() { }
func (n *Sequence) Terminate(status Status) { }

func (n *Sequence) IsSuccess() bool { return n.Status == SUCCESS }
func (n *Sequence) IsFailure() bool { return n.Status == FAILURE }
func (n *Sequence) IsRunning() bool { return n.Status == RUNNING }
func (n *Sequence) IsTerminated() bool { return n.Status == SUCCESS || n.Status == FAILURE }

func (n *Sequence) Reset() { n.Status = INVALID }

func (n *Sequence) Tick() Status {
  if n.Status != RUNNING { n.Initialize() }
  status := n.Update()
  if n.Status != RUNNING { n.Terminate(status) }

  return status
}

// COMPOSITE SECTION
func (n *Sequence) IsEmpty() bool {
  return len(n.Children) == 0
}

func (n *Sequence) AddChildren(children ...Behavior) {
  n.Children = append(n.Children, children...)
}
