// AUTOGENERATED FILE. DO NOT EDIT IT

// template behavior.go

package ai

import (
  "game/pidgeot-socket/ecs"
)

type Test struct {
  Status Status
  World *ecs.Manager
  Eid ecs.EID
}

func NewTest(eid ecs.EID, world *ecs.Manager) *Test {
	return &Test{
    World: world,
    Eid: eid,
  }
}

func (n *Test) Update() Status {
  c, err := n.World.GetComponent(n.Eid, ecs.CollisionComponent)
  if err == nil {
    collision := (*c).(*ecs.Collision)
    collision.ImpulseX = -1

    return SUCCESS
  }

  return FAILURE
}



func (n *Test) Initialize() { }
func (n *Test) Terminate(status Status) { }

func (n *Test) IsSuccess() bool { return n.Status == SUCCESS }
func (n *Test) IsFailure() bool { return n.Status == FAILURE }
func (n *Test) IsRunning() bool { return n.Status == RUNNING }
func (n *Test) IsTerminated() bool { return n.Status == SUCCESS || n.Status == FAILURE }

func (n *Test) Reset() { n.Status = INVALID }

func (n *Test) Tick() Status {
  if n.Status != RUNNING { n.Initialize() }
  status := n.Update()
  if n.Status != RUNNING { n.Terminate(status) }

  return status
}
